### ISSUE TITLE
In Safari Given css is not applying

### ISSUE THREAD

**Issue by pawan-logiciel** [justifi-tech/web-component-library#236] opened 2023-11-30 13:10 UTC
In iOS / Safari CSS we pass to modify UI is not working

This is how I am passing css
``` 
:root {
        --jfi-form-control-color: #111;
        --jfi-form-control-padding: 10px 12px 10px 12px;
        --jfi-layout-form-control-spacing-x: 16px;
        --jfi-layout-form-control-spacing-y: 16px;
        --jfi-layout-font-family: 'Roboto',sans-serif;
        --jfi-form-control-border-width: 1px;
        --jfi-form-control-border-style: solid;
        --jfi-form-control-border-color: #E0E0E0;
        --jfi-form-control-border-radius: 4px;
        --jfi-form-control-border-color-focus: #b8d3eb;
        --jfi-form-control-font-weight: 400;
        --jfi-form-control-font-size: 14px;
        --jfi-form-label-font-size: 14px;
        --jfi-form-label-color: #444;
        --jfi-form-label-margin: 0 0 5px 0;
        --jfi-form-label-font-weight: 400;
        --jfi-form-label-font-family: 'Roboto',sans-serif;
        --jfi-error-message-color: rgb(200, 27, 27);
        --jfi-error-message-margin: 5px 0 0 0;
        --jfi-error-message-font-size: 12px;
      }
```

This works fine on android / Chrome

**Comment by nhalm** [comment] 2024-02-14 16:44
Hi @pawan-logiciel.

Is this still an issue?  Since we cannot reproduce this, I am going to close the issue for now.  Please let us know if it pops back up!

**Closed by nhalm** 2024-02-14 16:44 UTC
Labels: bug, needs info

**Comment by pawan-logiciel** [comment] 2024-02-20 08:48
Yes @nhalm it's still an issue i am asking here about payment page
![image](https://github.com/justifi-tech/web-component-library/assets/46339496/b09df3b0-e17a-4937-93e0-bd38f0dfdadc)

CODE for this

```<justifi-bank-account-form validation-mode="onChange"></justifi-bank-account-form>```

**Comment by pawan-logiciel** [comment] 2024-02-20 08:49
@nhalm Please reopen this issue
