### ISSUE TITLE
Payment Method: 'Not Authenticated' Error During Customer Checkout

### ISSUE THREAD

**Issue by TiagoFuelber** [justifi-tech/web-component-library#227] opened 2023-11-10 21:07 UTC
**Overview**:
We've encountered a bug with our payment method web component. Several customers have reported receiving a "Not Authenticated" error during the checkout process. This issue seems to be linked to the authentication process managed by the web component.

**Steps to Reproduce**:
(Not clear yet)

**Expected Behavior**:
During checkout, the user should be authenticated seamlessly without encountering any error messages, allowing them to complete their purchase.

**Actual Behavior**:
In some cases, customers are receiving a "Not Authenticated" response during checkout, preventing them from completing their transaction.

**Additional Information**:

This issue does not occur consistently but has been reported by multiple customers.
Browser version: Not provided
Device: Not provided

We suspect that the issue might be related to how the authentication data is being handled or transmitted by the web component.
Potential Steps for Further Investigation:

Review the authentication process within the web component to identify any potential points of failure.
Test in different browsers.
https://www.cdhl.org/donate **(beware this is a live form do not use real credit card or bank account for testing)**
Attempt to reproduce the issue in a controlled environment using the steps mentioned above.
Check server logs for any related error messages or warnings during the authentication process.

Screenshots/Logs:
![image](https://github.com/justifi-tech/web-component-library/assets/22480988/621e7d18-a1d7-4229-9352-c7927daed6e7)

**Comment by nhalm** [comment] 2024-02-21 19:57
I'm not able to reproduce this on [the donate link](https://www.cdhl.org/donate).
As far as the 401 goes, I have seen this happen when the `client-id` and `account-id` props are not sent correctly.  It is possible that that is an issue here?  Given the way that the form works with the underlying iFrame it is hard to see a way that a 401 could result unless the props are incorrectly sent.  It there is an issue here I expect it is on the payments-js side of things.

**Comment by jakemer** [comment] 2024-04-18 14:57
This has gotten a bit old and it sounds like we were not able to reproduce the issue so I am closing it. If there are new occurrences we will revisit this.

**Closed by jakemer** 2024-04-18 14:57 UTC
Labels: bug
