### ISSUE TITLE
Checkout: Filter existing payment methods by payment method type

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#599] opened 2024-07-11 16:06 UTC
**Is your feature request related to a problem? Please describe.**
When `disable-credit-card` is passed to the checkout component the credit card form is being disabled. If a payment method group is passed with an existing credit card, that credit card is still visible. 
The same is true when `disable-bank-account` is passed and the payment method group includes a bank account.
If no payment method group is passed the current behavior is working correctly.

**Describe the solution you'd like**
Do not show existing payment methods of the type that is disabled via `disable-credit-card` or `disable-bank-account`. 
For example, if `disable-credit-card` is passed to the component do not show the credit card form and do not show existing credit cards in the passed payment method group.

**Describe alternatives you've considered**

**Additional context**

**Comment by jakemer** [comment] 2024-08-15 14:56
https://github.com/justifi-tech/web-component-library/issues/625 is a duplicate of this and both issues can be closed at the same time

**Comment by jakemer** [comment] 2024-08-16 14:31
Closing as duplicate

**Closed by jakemer** 2024-08-16 14:31 UTC
Labels: enhancement
